Candidate.create([
  { name: "Hillary Clinton (Democratic Party)" },
  { name: "Donald J. Trump (Republican Party)" },
  { name: "Gary Johnson (Libertarian Party)" },
  { name: "Dr. Jill Stein (Green Party)" },
  { name: "Darell Castle (Constitution Party of the US)" },
  { name: "Evan McMullin (Independent)" },
  { name: "Gloria LaRiva (Party of Socialism and Liberation)" },
  { name: "Rocky de la Fuente (Reform Party USA)" },
  { name: "Emidio Soltysik (Socialist Party USA)" },
  { name: "Alyson Kennedy (Socialist Workers Party)" },
  { name: "Frank Atwood (Approval Voting Party - Colorado)" },
  { name: "Scott Copeland (Constitution Party of Idaho-Texas)" },
  { name: "Richard Duncan (Independent)" },
  { name: "Princess Khadijah Jacob Fambro (Revolutionary Party)" },
  { name: "Jim Hedges (Prohibition Party)" },
  { name: "Tom Hoefling (America's Party)" },
  { name: "Lynn Kahn (Independent)" },
  { name: "Chris Keniston (Veterans Party of America)" },
  { name: "Kyle Kopitke (Independent American Party)" },
  { name: "Laurence Koltikoff (Independent)" },
  { name: "David Limbaugh (Independent)" },
  { name: "Bradford Lyttle (US Pacifist Party)" },
  { name: "Joseph Maidonado (Independent)" },
  { name: "Mike Maturen (American Solidarity Party)" },
  { name: "Monica Moorhead (Workers World Party)" },
  { name: "Ryan Scott (Independent)" },
  { name: "Rod Silva (Nutrition Party)" },
  { name: "Peter Skewes (American Party of SC)" },
  { name: "Mike Smith (Independent)" },
  { name: "Dan Vacek (Legal Marijuana Now Party)" },
  { name: "Jerry White (Socialist Equality Party)" }
])
